### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AlephAlpha** [AlephAlpha/rlifesrc#1]
只是一些想法，不一定真的要实现

- [ ] 更完善的测试
  - [ ] 检验细胞的 neighborhood descriptor 与其周围的细胞状态是否相符
  - [ ] 检验搜到的结果是否满足条件
  - [ ] 增加各种不同规则、不同对称性的测试；为此需找到适合用于的简单图样
- [ ] 给 `Status` 加个成员来表示未开始搜索的初始状态
  - [ ] TUI 和网页版相应地修改相关的提示
- [ ] 在初始状态下允许指定一些细胞的值
  - [ ] 想出一套合适的交互方式（鼠标左右键？）
- [ ] 允许指定一些细胞为不关心
- [ ] 允许搜索非周期性的图样，比如 parent
- [ ] 把不同的细胞状态显示成不同的颜色
- [ ] TUI 显示超过终端大小的图样，用方向键来移动显示的位置
- [ ] 存档，读档
  - [ ] 自动存档
- [ ] 支持斜着搜

斜着搜指的是：邻域的定义由

```
###
#_#
###
```

变成

```
  #
 # #
# _ #
 # #
  #
```
